server:
  port: 8080
  servlet:
    context-path:
spring:
  application:
    name: oss
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration